### ISSUE TITLE
Error log #1

### ISSUE THREAD

**Issue by RazorWolvendom** [VoltCruelerz/Greed#2]
![ScreenShot_20230929153947](https://github.com/VoltCruelerz/Greed/assets/44827474/0abbc691-9624-4aeb-bd80-af226beac237)

only few mods has that error when trying to interact with it in the list, any other mods are normal as supposed

**Comment by VoltCruelerz** [comment]
That error typically means the json is invalid. Can you send me the json in question?

**Comment by VoltCruelerz** [comment]
Talked on Discord. This is not a Greed error, but Greed's error logging for this situation will be improved in the next patch.
